version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/server
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=dine_hub
      - DB_USERNAME=root
      - DB_PASSWORD=root  # Đặt mật khẩu cho tài khoản root của MySQL

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root  # Thêm mật khẩu cho root
      MYSQL_DATABASE: dine_hub
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: