# version: '3.8'

# services:
#   server:
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     ports:
#       - "8000:80"
#     volumes:
#       - .:/var/www/html
#     environment:
#       - DB_HOST=db
#       - DB_PORT=3306
#       - DB_DATABASE=dine_hub
#       - DB_USERNAME=root
#       - DB_PASSWORD=root      
#     depends_on:
#       - db

#   db:
#     image: mysql:8
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: dine_hub
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:


version: "3.8"

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    volumes:
      - ./src:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: dine_hub_db
    environment:
      MYSQL_DATABASE: dine_hub
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dinehub
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"


  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
